version: "3.7"

services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spmon
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./docker-data/redis:/data